// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: funfact.proto

package funfact

import (
	context "context"
	common "github.com/tonytangau/cloud-native-rand/protos/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FunFactService_GetRandomFunFact_FullMethodName     = "/funfact.FunFactService/GetRandomFunFact"
	FunFactService_GetFunFactByCategory_FullMethodName = "/funfact.FunFactService/GetFunFactByCategory"
)

// FunFactServiceClient is the client API for FunFactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunFactServiceClient interface {
	GetRandomFunFact(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FunFactResponse, error)
	GetFunFactByCategory(ctx context.Context, in *common.CategoryRequest, opts ...grpc.CallOption) (*FunFactResponse, error)
}

type funFactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFunFactServiceClient(cc grpc.ClientConnInterface) FunFactServiceClient {
	return &funFactServiceClient{cc}
}

func (c *funFactServiceClient) GetRandomFunFact(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FunFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunFactResponse)
	err := c.cc.Invoke(ctx, FunFactService_GetRandomFunFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *funFactServiceClient) GetFunFactByCategory(ctx context.Context, in *common.CategoryRequest, opts ...grpc.CallOption) (*FunFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunFactResponse)
	err := c.cc.Invoke(ctx, FunFactService_GetFunFactByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunFactServiceServer is the server API for FunFactService service.
// All implementations must embed UnimplementedFunFactServiceServer
// for forward compatibility.
type FunFactServiceServer interface {
	GetRandomFunFact(context.Context, *emptypb.Empty) (*FunFactResponse, error)
	GetFunFactByCategory(context.Context, *common.CategoryRequest) (*FunFactResponse, error)
	mustEmbedUnimplementedFunFactServiceServer()
}

// UnimplementedFunFactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunFactServiceServer struct{}

func (UnimplementedFunFactServiceServer) GetRandomFunFact(context.Context, *emptypb.Empty) (*FunFactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomFunFact not implemented")
}
func (UnimplementedFunFactServiceServer) GetFunFactByCategory(context.Context, *common.CategoryRequest) (*FunFactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFunFactByCategory not implemented")
}
func (UnimplementedFunFactServiceServer) mustEmbedUnimplementedFunFactServiceServer() {}
func (UnimplementedFunFactServiceServer) testEmbeddedByValue()                        {}

// UnsafeFunFactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunFactServiceServer will
// result in compilation errors.
type UnsafeFunFactServiceServer interface {
	mustEmbedUnimplementedFunFactServiceServer()
}

func RegisterFunFactServiceServer(s grpc.ServiceRegistrar, srv FunFactServiceServer) {
	// If the following call pancis, it indicates UnimplementedFunFactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunFactService_ServiceDesc, srv)
}

func _FunFactService_GetRandomFunFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunFactServiceServer).GetRandomFunFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunFactService_GetRandomFunFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunFactServiceServer).GetRandomFunFact(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunFactService_GetFunFactByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunFactServiceServer).GetFunFactByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunFactService_GetFunFactByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunFactServiceServer).GetFunFactByCategory(ctx, req.(*common.CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunFactService_ServiceDesc is the grpc.ServiceDesc for FunFactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunFactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "funfact.FunFactService",
	HandlerType: (*FunFactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomFunFact",
			Handler:    _FunFactService_GetRandomFunFact_Handler,
		},
		{
			MethodName: "GetFunFactByCategory",
			Handler:    _FunFactService_GetFunFactByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "funfact.proto",
}
