// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: joke.proto

package joke

import (
	context "context"
	common "github.com/tonytangau/cloud-native-rand/protos/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JokeService_GetRandomJoke_FullMethodName     = "/joke.JokeService/GetRandomJoke"
	JokeService_GetJokeByCategory_FullMethodName = "/joke.JokeService/GetJokeByCategory"
)

// JokeServiceClient is the client API for JokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JokeServiceClient interface {
	GetRandomJoke(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JokeResponse, error)
	GetJokeByCategory(ctx context.Context, in *common.CategoryRequest, opts ...grpc.CallOption) (*JokeResponse, error)
}

type jokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJokeServiceClient(cc grpc.ClientConnInterface) JokeServiceClient {
	return &jokeServiceClient{cc}
}

func (c *jokeServiceClient) GetRandomJoke(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JokeResponse)
	err := c.cc.Invoke(ctx, JokeService_GetRandomJoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jokeServiceClient) GetJokeByCategory(ctx context.Context, in *common.CategoryRequest, opts ...grpc.CallOption) (*JokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JokeResponse)
	err := c.cc.Invoke(ctx, JokeService_GetJokeByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JokeServiceServer is the server API for JokeService service.
// All implementations must embed UnimplementedJokeServiceServer
// for forward compatibility.
type JokeServiceServer interface {
	GetRandomJoke(context.Context, *emptypb.Empty) (*JokeResponse, error)
	GetJokeByCategory(context.Context, *common.CategoryRequest) (*JokeResponse, error)
	mustEmbedUnimplementedJokeServiceServer()
}

// UnimplementedJokeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJokeServiceServer struct{}

func (UnimplementedJokeServiceServer) GetRandomJoke(context.Context, *emptypb.Empty) (*JokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomJoke not implemented")
}
func (UnimplementedJokeServiceServer) GetJokeByCategory(context.Context, *common.CategoryRequest) (*JokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJokeByCategory not implemented")
}
func (UnimplementedJokeServiceServer) mustEmbedUnimplementedJokeServiceServer() {}
func (UnimplementedJokeServiceServer) testEmbeddedByValue()                     {}

// UnsafeJokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JokeServiceServer will
// result in compilation errors.
type UnsafeJokeServiceServer interface {
	mustEmbedUnimplementedJokeServiceServer()
}

func RegisterJokeServiceServer(s grpc.ServiceRegistrar, srv JokeServiceServer) {
	// If the following call pancis, it indicates UnimplementedJokeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JokeService_ServiceDesc, srv)
}

func _JokeService_GetRandomJoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokeServiceServer).GetRandomJoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JokeService_GetRandomJoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokeServiceServer).GetRandomJoke(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JokeService_GetJokeByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokeServiceServer).GetJokeByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JokeService_GetJokeByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokeServiceServer).GetJokeByCategory(ctx, req.(*common.CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JokeService_ServiceDesc is the grpc.ServiceDesc for JokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "joke.JokeService",
	HandlerType: (*JokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomJoke",
			Handler:    _JokeService_GetRandomJoke_Handler,
		},
		{
			MethodName: "GetJokeByCategory",
			Handler:    _JokeService_GetJokeByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "joke.proto",
}
